# Generated by Django 4.2.13 on 2024-05-11 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('review', models.TextField(blank=True)),
                ('address', models.TextField(blank=True)),
                ('opentime', models.TextField(blank=True)),
                ('call', models.TextField(blank=True)),
            ],
        ),
    ]
