# Generated by Django 4.2.13 on 2024-05-11 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_remove_location_id_alter_location_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='image',
            field=models.ImageField(default='default.png', upload_to='location/'),
        ),
    ]
