# Generated by Django 4.2.13 on 2024-05-11 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_location_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
